<?php
return ['messages'=>['2d1dfdf73a616bee8783ad23fb2cf13b'=>'Com o objetivo de ampliar o acesso a serviços financeiros no Panamá, a Financiera FinanCard lançou o <a style="color: #ff6600;" href="https://financard.com.pa/easi/">EASI by Financard</a>, uma carteira digital associada a um cartão pré-pago Mastercard processado pela Evertec. A ferramenta permite que os usuários recarreguem saldo com facilidade, realizem compras em estabelecimentos físicos e online, façam cobranças recorrentes e transfiram dinheiro de forma instantânea para outros usuários dentro do aplicativo.<br><br>O lançamento não apenas amplia o portfólio da Financiera FinanCard, mas também fortalece a inclusão financeira ao oferecer uma alternativa acessível e moderna para a população não bancarizada, facilitando transações seguras e em tempo real.<br><br>Jimmy Solano Blanco, Country Manager de Centroamérica na Evertec, destaca:<br><blockquote>"Esta visão da Financiera FinanCard ao implementar o EASI by Financard representa um passo importante para a inclusão financeira no Panamá. Na Evertec, temos muito orgulho de ser o parceiro tecnológico que apoia esta iniciativa, facilitando a aceitação de carteiras e meios de pagamento que tornam as transações mais simples, seguras e eficientes. Este projeto reflete nosso compromisso conjunto com a transformação do ecossistema de pagamentos no Panamá."</blockquote><br>Parabenizamos a Financiera FinanCard por este marco importante e reafirmamos nosso compromisso em continuar promovendo a digitalização e a modernização do sistema financeiro no Panamá e em toda a região.','<p>En busca de ampliar el acceso a los servicios financieros en Panamá, Financiera FinanCard ha lanzado <a style="color: #ff6600;" href="https://financard.com.pa/easi/">EASI by Financard</a>, una billetera digital asociada a una tarjeta prepago Mastercard procesada por Evertec. Esta innovadora herramienta les permite a los usuarios recargar fondos fácilmente, realizar compras en comercios físicos y en línea, cargos recurrentes y transferir dinero de manera instantánea a otros usuarios dentro de la aplicación.</p>
<p>Este lanzamiento no solo expande la oferta de Financiera FinanCard, sino que también impulsa la inclusión financiera al ofrecer una alternativa accesible y moderna para la población no bancarizada facilitando transacciones seguras y en tiempo real.</p>
<blockquote><p>"La visión de Financiera FinanCard al implementar EASI by Financard es un paso significativo hacia la inclusión financiera en Panamá. En Evertec, nos enorgullece ser el socio tecnológico que apoya esta iniciativa, facilitando la aceptación de billeteras y medios de pago que hacen las transacciones más fáciles, seguras y eficientes. Este proyecto refleja nuestro compromiso compartido de transformar el ecosistema de pagos en Panamá."</p>
<p><cite>Jimmy Solano Blanco,<br />
Country Manager de Centroamérica para Evertec</cite></p></blockquote>
<p>Felicitamos a Financiera FinanCard por este importante hito y reafirmamos nuestro compromiso de seguir impulsando la digitalización y modernización del sistema financiero en Panamá y la región.</p>

'=>'Com o objetivo de ampliar o acesso a serviços financeiros no Panamá, a Financiera FinanCard lançou o <a style="color: #ff6600;" href="https://financard.com.pa/easi/">EASI by Financard</a>, uma carteira digital associada a um cartão pré-pago Mastercard processado pela Evertec. A ferramenta permite que os usuários recarreguem saldo com facilidade, realizem compras em estabelecimentos físicos e online, façam cobranças recorrentes e transfiram dinheiro de forma instantânea para outros usuários dentro do aplicativo.<br><br>O lançamento não apenas amplia o portfólio da Financiera FinanCard, mas também fortalece a inclusão financeira ao oferecer uma alternativa acessível e moderna para a população não bancarizada, facilitando transações seguras e em tempo real.<br><br>Jimmy Solano Blanco, Country Manager de Centroamérica na Evertec, destaca:<br><blockquote>"Esta visão da Financiera FinanCard ao implementar o EASI by Financard representa um passo importante para a inclusão financeira no Panamá. Na Evertec, temos muito orgulho de ser o parceiro tecnológico que apoia esta iniciativa, facilitando a aceitação de carteiras e meios de pagamento que tornam as transações mais simples, seguras e eficientes. Este projeto reflete nosso compromisso conjunto com a transformação do ecossistema de pagamentos no Panamá."</blockquote><br>Parabenizamos a Financiera FinanCard por este marco importante e reafirmamos nosso compromisso em continuar promovendo a digitalização e a modernização do sistema financeiro no Panamá e em toda a região.']];
